variables:
  - template: pipeline-templates/global-variables.yml
trigger:
  branches:
    include:
      - master
      - release-*
  paths:
    exclude:
      - README.md
pr: none
jobs:
  - job: Build
    displayName: 'Build and publish .NET Standard SDK and .NET Framework GUI component'
    variables:
      - template: pipeline-templates/job-variables.yml
    pool:
      vmImage: 'windows-latest'
    steps:
      - template: pipeline-templates/build-steps.yml
      - task: AzureKeyVault@2
        inputs:
          azureSubscription: 'SafeguardOpenSource'
          KeyVaultName: 'SafeguardBuildSecrets'
          SecretsFilter: 'NugetOrgApiKey'
        displayName: 'Get Nuget.Org API key from Sandbox Azure Key Vault'
      - task: NuGetCommand@2
        inputs:
          command: 'custom'
          arguments: 'push $(Build.ArtifactStagingDirectory)\*.nupkg -source https://api.nuget.org/v3/index.json -ApiKey $(NugetOrgApiKey) -NonInteractive -Verbosity detailed'
        displayName: 'Publishing NuGet packages to NuGet.org'
